apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: dev
data:
  USERNAME: admin
  DATABASE_URL: mongodb-svc

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: dev
type: opaque
data:
  PASSWORD: cGFzcw==

  
