apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limit-range
  namespace: dev
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: "500m"
      memory: 512Mi
    max:
      cpu: "1.5"
      memory: 1Gi
    min: 
      cpu: "200m"
      memory: 300Mi
    type: Container
