apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp-deploy
  namespace: dev
  labels:
    app: springapp
spec:
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
      - name: springapp-container
        image: vistein12/springapp:1.0
        resources:
          requests:
            cpu: "200m"
            memory: "250Mi"
          limits:
            cpu: "200m"
            memory: "250Mi"
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: USERNAME
        - name: MONGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: PASSWORD
        - name: MONGO_DB_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: DATABASE_URL

---
apiVersion: v1
kind: Service
metadata:
  name: springapp-svc
  namespace: dev
spec:
  selector:
    app: springapp
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080