Cluster Autoscaler
==================== 
The Kubernetes Cluster Autoscaler automatically adjusts the number of nodes in your cluster when pods fail or are rescheduled onto other nodes.
The Cluster Autoscaler is typically installed as a Deployment in your cluster. 
It uses leader election to ensure high availability, but scaling is done by only one replica at a time.


Create Autoscaler Role and attach it to worker group nodes

{
    "Version": "2012-10-17",
    "Statement": [
        {
           
            "Action": [
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeAutoScalingGroups",
                "ec2:DescribeLaunchTemplateVersions",
                "autoscaling:DescribeTags",
                "autoscaling:DescribeLaunchConfigurations",
                "ec2:DescribeInstanceTypes"
            ],

            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}

Deploy Cluster Autoscaler
==========================
Update name of your cluster in the cluster-autoscaler-autodiscover.yaml file

-> curl -O https://raw.githubusercontent.com/kubernetes/autoscaler/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml

command: kubectl apply -f cluster-autoscaler-autodiscover.yaml

