Volumes
===================
A Container's file system lives only as long as the Container does. So when a Container
terminates and restarts, filesystem changes are lost.
Volumes in Kubernetes are very easy to manage. It is basically a directory that gets mounted to a pod.


What is hostPath volume?
A hostPath volume mounts a file or directory from the host node's filesystem into your Pod


What is emptyDir volume?
An emptyDir volume is first created when a Pod is assigned to a nodem and exists as long as that Pod is running on that node
When a Pod is removed from a node for any reason, the data in the emptyDir is deleted permanently.

Use Cases
Holding files that a content-manager container fetches while a webserver container servers the data


StatefulSet
==============
This is designed for deploying and managing stateful Applications