apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpadeploymentautoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 2
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 20

---
apiVersion: v1
kind: Service
metadata:
  name: hpaclusterservice
spec:
  selector:
    app: hpapod
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
