apiVersion: v1
kind: PersistenVolumeClaim
metadata: 
  name: pvc
  namespace: podNamespace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: storage-class-name