# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: default

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false
  minReplicas: 5
  maxReplicas: 10

# targetCpuUtilization: 5
# targetMemoryUtilization: 20


minAvailable: 2
minAvailableProd: 4

apps:
  - app:
    name: pro-nginx
    targetCpuUtilization: 20
    targetMemoryUtilization: 40
  - app:
    name: namespace
  - app:
    name: tomcat-app
    targetCpuUtilization: 15
    targetMemoryUtilization: 50    
  - app:
    name: ingress

 
# app.kubernetes.io/instance=nginx-ingress
# app.kubernetes.io/name=nginx-ingress
# app.kubernetes.io/version=3.2

# apiVersion: v1
# kind: Service
# metadata:
#   name: hpaclusterservice
# spec:
#   selector:
#     app: hpapod
#   type: ClusterIP
#   ports:
#     - targetPort: 80
#       port: 80