apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  namespace: {{ .Values.namespace.env | default .Values.defaultEnv }}
type: {{ .Values.secret.type }}
{{- with .Values.secret.data }}
data:
    {{- toYaml . | nindent 4 }}
{{- end }}