apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}express-svc"
  namespace: {{ .Values.namespace.env | .Values.namespace.defaultEnv }}
spec:
  selector:
    app: mongo-express
  type: NodePort
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 31000

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: dev
spec:
  selector:
    app: mongodb
  clusterIP: None # Headless Service
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc"
  namespace: {{ .Values.namespace.env | default .Values.namespace.defaultEnv }}
  labels:
    {{- include "mongo-stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mongo-stack.selectorLabels" . | nindent 4 }}