apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc"
  namespace: {{ .Values.namespace.env | default .Values.namespace.defaultEnv }}
  labels:
    {{- include "mongo-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mongo-ui.selectorLabels" . | nindent 4 }}