apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: dev
  labels:
    app: mongodb
spec:
  strategy:
    type: Recreate
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
          - containerPort: 27017
          resources:
            requests:
              cpu: 400m
              memory: 500Mi
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: PASSWORD
          volumeMounts:
            - name: mongodb-volume
              mountPath: /data/db
      volumes:
        - name: mongodb-volume
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: dev
spec:
  storageClassName: "gp2"
  resources:
    requests:
      storage: 2Gi
  accessModes:
  - ReadOnlyMany

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongo-pv
# spec:
#   pesistentVolumeReclaimPolicy: # Retain Delete, Recycle 
#   capacity:
#     storage: 2Gi
#   accessModes:
#   - ReadWriteMany
#   nfs:
#     server: 10.100.0.136
#     path: / 
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: dev
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
  - targetPort: 27017
    port: 27017
    protocol: TCP
