apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: dev
spec:
  selector:
    app: mongodb
  clusterIP: None # Headless Service
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP