apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-ui
  namespace: dev
  labels:
    app: mongo-express
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: mongo-express
  replicas: 1
  template:
    metadata:
      name: mongo-ui
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
          - containerPort: 8081
          env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
            valueFrom:
              secretKeyRef:
                name: mongo-ui-secret
                key: USERNAME
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-ui-secret
                key: PASSWORD
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongo-ui-config
                key: DATABASE_URL
          resources:
            requests:
              cpu: 400m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 550Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-ui-svc
  namespace: dev
spec:
  selector:
    app: mongo-express
  type: NodePort
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 31000
