apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-pv
  namespace: dev
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: fs-01bbbc5af89cb868b.efs.us-east-2.amazonaws.com
    path: /