apiVersion: v1
kind: Service
metadata:
  name: serviceName
  namespace: serviceNamespace
spec:
  selector:
    app: app-name
  type: clusterIP
  ports:
  - name: nameService
    protocol: TCP
    port: portNumber
    targetPort: containerPort   